### ISSUE TITLE
Winning team is reversed.

### ISSUE THREAD

**Issue by alex9smith** [alex9smith/ascendant#14]
https://www.dota2stats.io/match/489968183
Should show DHL winning. 

Probably also the cause of all heroes on team summary pages showing 100% win rate.

**Comment by LonelyCat124** [comment]
Think this just shows radiant always.

**Comment by LonelyCat124** [comment]
Think I identified the bug in the python code - I'll have a fix up tonight I hope.

**Comment by LonelyCat124** [comment]
Fixed in #21
