### ISSUE TITLE
Partial match?

### ISSUE THREAD

**Issue by LonelyCat124** [alex9smith/ascendant#17]
https://www.dota2stats.io/match/4904105744

This match somehow has a 3v0, not sure quite how that happened - happy to look at the replay with python if its a consistent error.

**Comment by LonelyCat124** [comment]
Same with any other replays you have issues with - send me either the yml + metadata or replay and I can have a look.

**Comment by alex9smith** [comment]
Is this the team with G in? It inserts players one at a time so it's probably got to him and failed. Fixing #15 and reparsing should sort this one.
