### ISSUE TITLE
Hash player IDs in url

### ISSUE THREAD

**Issue by LonelyCat124** [alex9smith/ascendant#25]
Not sure that we should have the player steam IDs in the url, could hash them somehow to make them less easy to read? Not a major issue but just makes me slightly uncomfortable (i think dotabuff and opendota use a shortened or something version)

**Comment by alex9smith** [comment]
That's a fair point. I'll hash the IDs in the URL and links, and decrypt them in the API wrapper.

**Comment by alex9smith** [comment]
Actually no. I'll add the hashed ID when we insert the player to the DB as an extra column (since we want the raw ID to look up against the steam API)
